export const GET_RATES = 'GET_RATES';
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS';
export const GET_RATES_ERROR = 'GET_RATES_ERROR';

export const GET_AVE_INTEREST = 'GET_AVE_INTEREST';
export const GET_AVE_INTEREST_SUCCESS = 'GET_AVE_INTEREST_SUCCESS';

export const SAVE_INPUT = 'SAVE_INPUT';
export const SAVE_MONTHLY_REPAYMENT = 'SAVE_MONTHLY_REPAYMENT';

